In [1]:
import numpy as np
from pr3_utils import *

In [2]:
t = 0
features = 0
linear_velocity = 0
angular_velocity = 0
K = 0
b = 0
imu_T_cam = 0

In [3]:
if __name__ == '__main__':
    # Load the measurements
    filename = "./data/10.npz"
    t,features,linear_velocity,angular_velocity,K,b,imu_T_cam = load_data(filename)

    # (a) IMU Localization via EKF Prediction

    # (b) Landmark Mapping via EKF Update

    # (c) Visual-Inertial SLAM

    # You can use the function below to visualize the robot pose over time
    # visualize_trajectory_2d(world_T_imu, show_ori = True)

In [4]:
print(t[0].shape)
print(t)

(3026,)
[[1.36974249e+09 1.36974249e+09 1.36974249e+09 ... 1.36974280e+09
  1.36974280e+09 1.36974280e+09]]


In [12]:
print(features.shape)
# features[:, :, t] this will help me find the features at time t
print(features[:, :, 0].shape)
print(features[:, 55, 0])

first = features[:, :, 0]
# print(); print("First"); print(first.shape)
# np.where( np.all(arr == np.array([10,15,30]), axis=-1) )

not_needed = np.array([-1. ,-1., -1., -1.])
only_required = np.where((first[0, :]!=-1) & (first[1, :]!=-1) & (first[2, :]!=-1) & (first[3, :]!=-1))
# non_identified = np.where(first == not_needed)
_, M, _ = np.nan, np.nan, np.nan
# print(); print("Only required"); print(first[:, only_required].shape); print(first[:, only_required])

(4, 13289, 3026)
(4, 13289)
[1278.50036621  257.12567139 1232.65490723  257.28314209]


In [ ]:
# With linear_velocity and angular velocity it becomes 6-dimensional
print("Linear Velocity")
print(linear_velocity.shape)
# print(linear_velocity)

print()
print("Angular Velocity")
print(angular_velocity.shape)
# print(angular_velocity)

In [ ]:
linear_velocity[:, 10]

In [4]:
# The most important; K matrix for camera frame
print("K")
print(K.shape)
print(K)

K
(3, 3)
[[552.554261   0.       682.049453]
 [  0.       552.554261 238.769549]
 [  0.         0.         1.      ]]


In [6]:
# The base line of the camera
print("Baseline")
print(b.shape)
print(b)

Baseline
()
0.6


In [7]:
print("Pose of IMU")
print(imu_T_cam.shape)
print(imu_T_cam)

Pose of IMU
(4, 4)
[[ 0.03717833 -0.09861822  0.9944306   1.5752681 ]
 [ 0.99926755 -0.00535534 -0.03789026  0.00439141]
 [ 0.00906218  0.99511094  0.09834688 -0.65      ]
 [ 0.          0.          0.          1.        ]]
